branches:
    only:
        - master
        - kaldi-patch

compiler:
    - g++

# settings according http://blog.travis-ci.com/2012-12-18-travis-artifacts/#How-to-use%3F
env:
 global:
   - "ARTIFACTS_AWS_REGION=us-east-1"
   - "ARTIFACTS_S3_BUCKET=ufal-dsg"
   - secure: "HZz2n4K+PWjd9Sw3z3IRYFmnkYKGZGlX6Z64qdq3d7Rc3fRhZ4HSfq1Ie0/oQO7de7TvbcCvCtlPnj+y6Ca5xkq5GnqAM7FFriy3AyQDqF/Cq/SuH6VGo6WqNpVTwKgT7+6/kbTCVcZ5BlkkGd0Y6K5MVGY7s59jkYznVbvwKMk="
   - secure: "dlODcY+FHeHHHXXh/qQp7Bg0vazghLVbBCTnV3g8CtAuraS2ETKyc+lJ3orseY20v0OcnzsDXXqlFUQJppz05ayKokbyhbEKhG4v18l9TJ0doqQYrEjHiSGy1Etrxv5WeeJ12dJVM/zj83oMzRbhi3Jjv+uVpYuKvPb8kAFHRk0="

language: cpp

install:
    - mkdir travis-openfst
    - ./configure --prefix=`pwd`/travis-openfst --enable-static --enable-shared --enable-far --enable-ngram-fsts CXX=g++ LIBS="-ldl"
    - make install
    - pushd travis-openfst ; [ -d lib64 ] && [ ! -d lib ] && ln -s lib64 lib  ; popd

before_script:
    - "gem install travis-artifacts"

script:
    - echo No tests TODO Just uploading to Amazon S3

after_success: # and this only on success
    - cp Makefile travis-openfst/Makefile  # Kaldi requires it for checking which openfst version is used
    - tar cvzf travis-openfst.tar.gz travis-openfst
    - if [[ $TRAVIS_BRANCH == 'kaldi-patch' ]] ; then travis-artifacts upload --path travis-openfst.tar.gz --target-path openfst ; fi
    # - travis-artifacts upload --path travis-openfst.tar.gz --target-path artifacts/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID # debugging
